using uhigh.Net.Diagnostics;
using uhigh.Net.Parser;
using System.Text;
using System.Collections.Generic;

namespace uhigh.Net.CodeGen
{
    /// <summary>
    /// Java code generator for μHigh programs
    /// </summary>
    public class JavaGenerator : ICodeGenerator
    {
        private readonly StringBuilder _output = new();
        private int _indentLevel = 0;
        private DiagnosticsReporter _diagnostics = new();
        private HashSet<string> _imports = new();

        // μHigh type to Java type mapping table
        private static readonly Dictionary<string, string> TypeMappings = new(StringComparer.OrdinalIgnoreCase)
        {
            { "int", "int" },
            { "long", "long" },
            { "float", "float" },
            { "double", "double" },
            { "decimal", "double" },
            { "byte", "byte" },
            { "sbyte", "byte" },
            { "short", "short" },
            { "ushort", "short" },
            { "uint", "int" },
            { "ulong", "long" },
            { "bool", "boolean" },
            { "true", "true" },
            { "false", "false" },
            { "string", "String" },
            { "char", "char" },
            { "Guid", "String" },
            { "object", "Object" },
            { "array", "ArrayList<Object>" },
            { "Dictionary", "HashMap<Object, Object>" },
            { "Set", "HashSet<Object>" },
            { "Tuple", "Object[]" },
            { "string[]", "String[]" }
        
        };

        public CodeGeneratorInfo Info => new()
        {
            Name = "JavaGenerator",
            Description = "Java code generator for μHigh programs",
            Version = "1.0.0",
            SupportedFeatures = new List<string> { "Classes", "Methods", "Types", "Imports" },
            RequiredDependencies = new List<string> { "java.base" }
        };

        public string TargetName => "Java";
        public string FileExtension => ".java";

        public void Initialize(CodeGeneratorConfig config, DiagnosticsReporter diagnostics)
        {
            _diagnostics = diagnostics;
            _output.Clear();
            _indentLevel = 0;
            _imports.Clear();
        }

        public bool CanGenerate(Program program, DiagnosticsReporter diagnostics)
        {
            // Basic validation, can be extended
            return true;
        }

        public string Generate(Program program, DiagnosticsReporter? diagnostics = null, string? rootNamespace = null, string? className = null)
        {

            _output.Clear();
            _output.AppendLine("// Generated by μHigh JavaGenerator");
            _output.AppendLine("import java.util.*;");
            if (rootNamespace != null)
            {
                _output.AppendLine($"package {rootNamespace};");
                _output.AppendLine();
            }
            foreach (var stmt in program.Statements)
            {
                GenerateStatement(stmt);
            }
            return _output.ToString();
        }

        private void GenerateStatement(Statement stmt)
        {
            switch (stmt)
            {
                case ClassDeclaration cls:
                    GenerateClass(cls);
                    break;
                case MethodDeclaration method:
                    GenerateMethod(method, isTopLevel: true);
                    break;
                case FieldDeclaration field:
                    GenerateField(field);
                    break;
                case PropertyDeclaration prop:
                    GenerateProperty(prop);
                    break;
                case EnumDeclaration en:
                    GenerateEnum(en);
                    break;
                case InterfaceDeclaration iface:
                    GenerateInterface(iface);
                    break;
                case NamespaceDeclaration ns:
                    // Java only supports one package per file, so skip
                    break;
                case ImportStatement imp:
                    _output.AppendLine($"import {imp.ClassName};");
                    break;
                case ExpressionStatement exprStmt:
                    Indent();
                    _output.Append(GenerateExpression(exprStmt.Expression));
                    _output.AppendLine(";");
                    break;
                case VariableDeclaration varDecl:
                    Indent();
                    var type = varDecl.Type ?? "Object";
                    _output.Append($"{MapType(type)} {varDecl.Name}");
                    if (varDecl.Initializer != null)
                        _output.Append($" = {GenerateExpression(varDecl.Initializer)}");
                    _output.AppendLine(";");
                    break;
                case IfStatement ifStmt:
                    GenerateIf(ifStmt);
                    break;
                case ForStatement forStmt:
                    GenerateFor(forStmt);
                    break;
                case WhileStatement whileStmt:
                    GenerateWhile(whileStmt);
                    break;
                case ReturnStatement retStmt:
                    Indent();
                    _output.Append("return");
                    if (retStmt.Value != null)
                        _output.Append($" {GenerateExpression(retStmt.Value)}");
                    _output.AppendLine(";");
                    break;
                case BreakStatement:
                    Indent();
                    _output.AppendLine("break;");
                    break;
                case ContinueStatement:
                    Indent();
                    _output.AppendLine("continue;");
                    break;
                default:
                    Indent();
                    _output.AppendLine("// Unsupported statement type: " + stmt.GetType().Name);
                    break;
            }
        }

        private void GenerateClass(ClassDeclaration cls)
        {
            Indent();
            var mods = cls.IsPublic ? "public " : "";
            _output.Append($"{mods}class {cls.Name}");
            if (!string.IsNullOrEmpty(cls.BaseClass))
                _output.Append($" extends {cls.BaseClass}");
            if (cls.GenericParameters.Count > 0)
                _output.Append("<" + string.Join(", ", cls.GenericParameters) + ">");
            _output.AppendLine(" {");
            _indentLevel++;
            foreach (var member in cls.Members)
                GenerateStatement(member);
            _indentLevel--;
            Indent();
            _output.AppendLine("}");
        }

        private void GenerateMethod(MethodDeclaration method, bool isTopLevel = false)
        {
            Indent();
            var mods = method.IsStatic ? "static " : "";
            if (method.Modifiers.Contains("public")) mods = "public " + mods;
            var retType = method.IsConstructor ? "" : MapType(method.ReturnType ?? "void");
            var name = method.IsConstructor ? method.Name : $"{retType} {method.Name}";
            _output.Append($"{mods}{name}(");
            _output.Append(string.Join(", ", method.Parameters.ConvertAll(p => $"{MapType(p.Type ?? "Object")} {p.Name}")));
            _output.Append(") {");
            _output.AppendLine();
            _indentLevel++;
            foreach (var stmt in method.Body)
                GenerateStatement(stmt);
            _indentLevel--;
            Indent();
            _output.AppendLine("}");
        }

        private void GenerateField(FieldDeclaration field)
        {
            Indent();
            var mods = field.Modifiers.Contains("public") ? "public " : "";
            if (field.IsStatic) mods += "static ";
            if (field.IsReadonly) mods += "final ";
            var type = MapType(field.Type ?? "Object");
            _output.Append($"{mods}{type} {field.Name}");
            if (field.Initializer != null)
                _output.Append($" = {GenerateExpression(field.Initializer)}");
            _output.AppendLine(";");
        }

        private void GenerateProperty(PropertyDeclaration prop)
        {
            Indent();
            var mods = prop.Modifiers.Contains("public") ? "public " : "";
            if (prop.IsStatic) mods += "static ";
            var type = MapType(prop.Type ?? "Object");
            _output.Append($"{mods}{type} {prop.Name}");
            if (prop.Initializer != null)
                _output.Append($" = {GenerateExpression(prop.Initializer)}");
            _output.AppendLine(";");
            // Java doesn't support C#-style properties, so treat as field
        }

        private void GenerateEnum(EnumDeclaration en)
        {
            Indent();
            var mods = en.Modifiers.Contains("public") ? "public " : "";
            _output.AppendLine($"{mods}enum {en.Name} {{");
            _indentLevel++;
            for (int i = 0; i < en.Members.Count; i++)
            {
                Indent();
                _output.Append(en.Members[i].Name);
                if (en.Members[i].Value != null)
                {
                    var exprStr = GenerateExpression(en.Members[i].Value);
                    if (!string.IsNullOrEmpty(exprStr))
                        _output.Append($" = {exprStr}");
                }
                if (i < en.Members.Count - 1)
                    _output.Append(", ");
            }
            _output.AppendLine();
            _indentLevel--;
            Indent();
            _output.AppendLine("}");
        }

        private void GenerateInterface(InterfaceDeclaration iface)
        {
            Indent();
            var mods = iface.Modifiers.Contains("public") ? "public " : "";
            _output.Append($"{mods}interface {iface.Name}");
            if (iface.BaseInterfaces.Count > 0)
                _output.Append(" extends " + string.Join(", ", iface.BaseInterfaces));
            if (iface.GenericParameters.Count > 0)
                _output.Append("<" + string.Join(", ", iface.GenericParameters) + ">");
            _output.AppendLine(" {");
            _indentLevel++;
            foreach (var member in iface.Members)
                GenerateStatement(member);
            _indentLevel--;
            Indent();
            _output.AppendLine("}");
        }

        private void GenerateIf(IfStatement ifStmt)
        {
            Indent();
            _output.Append($"if ({GenerateExpression(ifStmt.Condition)}) {{");
            _output.AppendLine();
            _indentLevel++;
            foreach (var stmt in ifStmt.ThenBranch)
                GenerateStatement(stmt);
            _indentLevel--;
            if (ifStmt.ElseBranch != null && ifStmt.ElseBranch.Count > 0)
            {
                Indent();
                _output.AppendLine("} else {");
                _indentLevel++;
                foreach (var stmt in ifStmt.ElseBranch)
                    GenerateStatement(stmt);
                _indentLevel--;
            }
            Indent();
            _output.AppendLine("}");
        }

        private void GenerateFor(ForStatement forStmt)
        {
            Indent();
            if (forStmt.IsForInLoop)
            {
                var type = "Object";
                _output.Append($"for ({type} {forStmt.IteratorVariable} : {GenerateExpression(forStmt.IterableExpression!)}) {{");
            }
            else
            {
                var init = forStmt.Initializer is VariableDeclaration vd ? $"{MapType(vd.Type ?? "Object")} {vd.Name} = {GenerateExpression(vd.Initializer!)}" : "";
                var cond = forStmt.Condition != null ? GenerateExpression(forStmt.Condition) : "";
                var inc = forStmt.Increment is ExpressionStatement es ? GenerateExpression(es.Expression) : "";
                _output.Append($"for ({init}; {cond}; {inc}) {{");
            }
            _output.AppendLine();
            _indentLevel++;
            foreach (var stmt in forStmt.Body)
                GenerateStatement(stmt);
            _indentLevel--;
            Indent();
            _output.AppendLine("}");
        }

        private void GenerateWhile(WhileStatement whileStmt)
        {
            Indent();
            _output.Append($"while ({GenerateExpression(whileStmt.Condition)}) {{");
            _output.AppendLine();
            _indentLevel++;
            foreach (var stmt in whileStmt.Body)
                GenerateStatement(stmt);
            _indentLevel--;
            Indent();
            _output.AppendLine("}");
        }

        private string GenerateExpression(Expression expr)
        {
            switch (expr)
            {
                case LiteralExpression lit:
                    if (lit.Value == null) return "null";
                    return lit.Type == uhigh.Net.Lexer.TokenType.String ? $"\"{lit.Value}\"" : lit.Value.ToString() ?? "null";
                case IdentifierExpression id:
                    return id.Name;
                case QualifiedIdentifierExpression qid:
                    return qid.Name;
                case BinaryExpression bin:
                    return $"{GenerateExpression(bin.Left)} {TokenToJavaOperator(bin.Operator)} {GenerateExpression(bin.Right)}";
                case ConstructorCallExpression ctor:
                    var ctorArgs = string.Join(", ", ctor.Arguments.ConvertAll(GenerateExpression));
                    return $"new {ctor.ClassName}({ctorArgs})";
                case UnaryExpression un:
                    var op = TokenToJavaOperator(un.Operator);
                    return un.IsPostfix ? $"{GenerateExpression(un.Operand)}{op}" : $"{op}{GenerateExpression(un.Operand)}";
                case CallExpression call:
                    // μHigh method mappings for Java
                    if (call.Function is IdentifierExpression fn)
                    {
                        var fnName = fn.Name;
                        var args = call.Arguments;
                        switch (fnName)
                        {
                            case "_add_to":
                                // Add_to(collection, element) => collection.add(element)
                                if (args.Count == 2)
                                    return $"{GenerateExpression(args[0])}.add({GenerateExpression(args[1])})";
                                break;
                            case "_remove_from":
                                // Remove_from(collection, element_or_index) => collection.remove(element_or_index)
                                if (args.Count == 2)
                                    return $"{GenerateExpression(args[0])}.remove({GenerateExpression(args[1])})";
                                break;
                            case "_length_of":
                                // Length_of(collection_or_string) => .size() for collections, .length() for strings
                                if (args.Count == 1)
                                    return $"{GenerateExpression(args[0])}{LengthOfSuffix(args[0])}";
                                break;
                            case "_index_of":
                                // Index_of(collection, index_or_key) => collection[index_or_key]
                                if (args.Count == 2)
                                    return $"{GenerateExpression(args[0])}[{GenerateExpression(args[1])}]";
                                break;
                            case "_substring_of":
                                // Substring_of(string, start, len) => string.substring(start, start+len)
                                if (args.Count == 3)
                                    return $"{GenerateExpression(args[0])}.substring({GenerateExpression(args[1])}, {GenerateExpression(args[1])} + {GenerateExpression(args[2])})";
                                break;
                            case "_toUpper":
                                // ToUpper(string) => string.toUpperCase()
                                if (args.Count == 1)
                                    return $"{GenerateExpression(args[0])}.toUpperCase()";
                                break;
                            case "_toLower":
                                // ToLower(string) => string.toLowerCase()
                                if (args.Count == 1)
                                    return $"{GenerateExpression(args[0])}.toLowerCase()";
                                break;
                            case "_contains_in":
                                // Contains_in(collection_or_string, element_or_substring)
                                if (args.Count == 2)
                                {
                                    // For strings: .contains(substring), for collections: .contains(element)
                                    return $"{GenerateExpression(args[0])}.contains({GenerateExpression(args[1])})";
                                }
                                break;
                            case "_print":
                                // Print(value) => System.out.println(value)
                                if (args.Count == 1)
                                    return $"System.out.println({GenerateExpression(args[0])})";
                                break;
                            case "_readLine":
                                // ReadLine() => new Scanner(System.in).nextLine()
                                if (args.Count == 0)
                                    return "new Scanner(System.in).nextLine()";
                                break;
                            case "_length":
                                // Length(string) => string.length()
                                if (args.Count == 1)
                                    return $"{GenerateExpression(args[0])}.length()";
                                break;
                        }
                    }
                    var callArgs = string.Join(", ", call.Arguments.ConvertAll(GenerateExpression));
                    return $"{GenerateExpression(call.Function)}({callArgs})";
                case MemberAccessExpression mem:
                    return $"{GenerateExpression(mem.Object)}.{mem.MemberName}";
                case ArrayExpression arr:
                    return $"new ArrayList<>(List.of({string.Join(", ", arr.Elements.ConvertAll(GenerateExpression))}))";
                case IndexExpression idx:
                    return $"{GenerateExpression(idx.Object)}[{GenerateExpression(idx.Index)}]";
                case AssignmentExpression assign:
                    return $"{GenerateExpression(assign.Target)} {TokenToJavaOperator(assign.Operator)} {GenerateExpression(assign.Value)}";
                case ThisExpression:
                    return "this";
                default:
                    return $"/* Unsupported expr: {expr.GetType().Name} */";
            }

        // Helper for Length_of: decide between .size() and .length()
        string LengthOfSuffix(Expression arg)
        {
            // If it's a string literal or identifier named 'String', use .length(), else .size()
            if (arg is IdentifierExpression id && id.Name.ToLower().Contains("str"))
                return ".length()";
            if (arg is LiteralExpression lit && lit.Type == uhigh.Net.Lexer.TokenType.String)
                return ".length()";
            return ".size()";
        }
        }

        private string MapType(string type)
        {
            if (TypeMappings.TryGetValue(type, out var mapped)) return mapped;
            return type;
        }

        private string TokenToJavaOperator(uhigh.Net.Lexer.TokenType op)
        {
            // Map μHigh token types to Java operators
            switch (op)
            {
                case Lexer.TokenType.Plus: return "+";
                case Lexer.TokenType.Minus: return "-";
                case Lexer.TokenType.Multiply: return "*";
                case Lexer.TokenType.Divide: return "/";
                case Lexer.TokenType.Modulo: return "%";
                case Lexer.TokenType.Assign: return "=";
                case Lexer.TokenType.Less: return "<";
                case Lexer.TokenType.Greater: return ">";
                case Lexer.TokenType.LessEqual: return "<=";
                case Lexer.TokenType.GreaterEqual: return ">=";
                case Lexer.TokenType.NotEqual: return "!=";
                case Lexer.TokenType.And: return "&&";
                case Lexer.TokenType.Or: return "||";
                case Lexer.TokenType.Not: return "!";
                case Lexer.TokenType.Increment: return "++";
                case Lexer.TokenType.Decrement: return "--";
                default: return op.ToString();
            }
        }

        private void Indent()
        {
            _output.Append(new string(' ', _indentLevel * 4));
        }

        public string Generate(List<Program> programs, DiagnosticsReporter? diagnostics = null, string? rootNamespace = null, string? className = null)
        {

            _output.Clear();
            _output.Clear();
            var importSet = new HashSet<string>();
            var topLevelStmts = new List<Statement>();

            // Collect imports and top-level statements
            foreach (var program in programs)
            {
                foreach (var stmt in program.Statements)
                {
                    if (stmt is ImportStatement imp)
                    {
                        importSet.Add(imp.ClassName);
                    }
                    else
                    {
                        topLevelStmts.Add(stmt);
                    }
                }
            }
            // should be first   line
            if (rootNamespace != null)
            {
                _output.AppendLine($"package {rootNamespace};");
                _output.AppendLine();
            }

            _output.AppendLine("// Generated by μHigh JavaGenerator (Combined)");
            _output.AppendLine("import java.util.*;");
            foreach (var imp in importSet)
            {
                _output.AppendLine($"import {imp};");
            }

            foreach (var stmt in topLevelStmts)
            {
                GenerateStatement(stmt);
            }

            return _output.ToString();

        }


        /// <summary>
        /// Generates a dictionary mapping Java filenames to their contents, one per top-level class or namespace per input Program.
        /// </summary>
        public Dictionary<string, string> GenerateMultipleFiles(List<Program> programs, DiagnosticsReporter? diagnostics = null, string? rootNamespace = null)
        {
            var result = new Dictionary<string, string>();
            foreach (var program in programs)
            {
                foreach (var stmt in program.Statements)
                {
                    if (stmt is NamespaceDeclaration ns)
                    {
                        foreach (var member in ns.Members)
                        {
                            if (member is ClassDeclaration cls)
                            {
                                _output.Clear();
                                _output.AppendLine("// Generated by μHigh JavaGenerator");
                                _output.AppendLine("import java.util.*;");
                                _output.AppendLine($"package {ns.Name};");
                                GenerateClass(cls);
                                var fileName = $"{cls.Name}.java";
                                result[fileName] = _output.ToString();
                            }
                        }
                    }
                    else if (stmt is ClassDeclaration cls)
                    {
                        _output.Clear();
                        _output.AppendLine("// Generated by μHigh JavaGenerator");
                        _output.AppendLine("import java.util.*;");
                        if (rootNamespace != null)
                            _output.AppendLine($"package {rootNamespace};");
                        GenerateClass(cls);
                        var fileName = $"{cls.Name}.java";
                        result[fileName] = _output.ToString();
                    }
                }
            }
            return result;
        }

        public string GenerateCombined(List<Program> programs, DiagnosticsReporter? diagnostics = null, string? rootNamespace = null, string? className = null)
        {
            _output.Clear();
            _indentLevel = 0;

            var combinedBuilder = new StringBuilder();
            var importSet = new HashSet<string>();
            var packageName = rootNamespace;

            foreach (var program in programs)
            {
                foreach (var stmt in program.Statements)
                {
                    switch (stmt)
                    {
                        case ImportStatement imp:
                            importSet.Add(imp.ClassName);
                            break;
                        case NamespaceDeclaration ns when string.IsNullOrEmpty(packageName):
                            packageName = ns.Name;
                            break;
                    }
                }
            }

            if (!string.IsNullOrEmpty(packageName))
            {
                combinedBuilder.AppendLine($"package {packageName};");
                combinedBuilder.AppendLine();
            }
            combinedBuilder.AppendLine("// Generated by μHigh JavaGenerator (Combined)");
            combinedBuilder.AppendLine("import java.util.*;");
            foreach (var imp in importSet)
            {
                combinedBuilder.AppendLine($"import {imp};");
            }

            foreach (var program in programs)
            {
                foreach (var stmt in program.Statements)
                {
                    if (stmt is ImportStatement)
                        continue;

                    var snippet = GenerateStatementSnippet(stmt);
                    if (!string.IsNullOrWhiteSpace(snippet))
                    {
                        combinedBuilder.AppendLine(snippet.TrimEnd());
                        combinedBuilder.AppendLine();
                    }
                }
            }

            var result = combinedBuilder.ToString().TrimEnd();
            _output.Clear();
            _indentLevel = 0;
            return string.IsNullOrEmpty(result) ? result : result + Environment.NewLine;
        }

        private string GenerateStatementSnippet(Statement stmt)
        {
            if (stmt is NamespaceDeclaration ns)
            {
                var namespaceBuilder = new StringBuilder();
                foreach (var member in ns.Members)
                {
                    var memberSnippet = GenerateStatementSnippet(member);
                    if (!string.IsNullOrWhiteSpace(memberSnippet))
                    {
                        namespaceBuilder.AppendLine(memberSnippet.TrimEnd());
                        namespaceBuilder.AppendLine();
                    }
                }
                return namespaceBuilder.ToString().TrimEnd();
            }

            var originalIndent = _indentLevel;
            var start = _output.Length;
            GenerateStatement(stmt);
            var length = _output.Length - start;
            if (length <= 0)
            {
                _indentLevel = originalIndent;
                return string.Empty;
            }

            var snippet = _output.ToString(start, length);
            _output.Remove(start, length);
            _indentLevel = originalIndent;
            return snippet.TrimEnd();
        }

        public string GenerateWithoutUsings(Program program, DiagnosticsReporter? diagnostics = null, string? rootNamespace = null, string? className = null)
        {
            throw new NotImplementedException();
        }

        public HashSet<string> GetCollectedUsings()
        {
            throw new NotImplementedException();
        }
    }
}