using System.Text;
using uhigh.Net.Diagnostics;
using uhigh.Net.Lexer;
using uhigh.Net.Parser;

namespace uhigh.Net.CodeGen
{
    /// <summary>
    /// MicroASM code generator for μHigh programs
    /// </summary>
    public class MicroAsmGenerator : ICodeGenerator
    {
        private readonly StringBuilder _output = new();
        private int _indentLevel = 0;
        private DiagnosticsReporter _diagnostics = new();
        private CodeGeneratorConfig? _config;
        private readonly HashSet<string> _includes = new();
        private readonly Dictionary<string, string> _variables = new();
        private int _labelCounter = 0;
        private readonly Stack<string> _labelStack = new();

        public CodeGeneratorInfo Info => new()
        {
            Name = "MicroASM Code Generator",
            Description = "Generates MicroASM assembly code from μHigh programs",
            Version = "1.0.0",
            SupportedFeatures = new() { "functions", "variables", "control-flow", "arithmetic", "io" },
            RequiredDependencies = new() { "MicroASM Runtime", "jmasm" }
        };

        public string TargetName => "microasm";
        public string FileExtension => ".masm";

        public void Initialize(CodeGeneratorConfig config, DiagnosticsReporter diagnostics)
        {
            _config = config;
            _diagnostics = diagnostics;
            diagnostics.ReportInfo("Initialized MicroASM generator");
        }

        public bool CanGenerate(Program program, DiagnosticsReporter diagnostics)
        {
            // Check for features not supported in MicroASM
            var unsupportedFeatures = new List<string>();

            foreach (var stmt in program.Statements)
            {
                if (stmt is ClassDeclaration)
                {
                    diagnostics.ReportWarning("Classes are not directly supported in MicroASM - will be flattened");
                }
                if (stmt is InterfaceDeclaration)
                {
                    unsupportedFeatures.Add("interfaces");
                }
                if (stmt is NamespaceDeclaration)
                {
                    diagnostics.ReportWarning("Namespaces will be flattened in MicroASM");
                }
            }

            foreach (var feature in unsupportedFeatures)
            {
                diagnostics.ReportError($"Unsupported feature for MicroASM: {feature}");
            }

            return unsupportedFeatures.Count == 0;
        }

        public string Generate(Program program, DiagnosticsReporter? diagnostics = null, string? rootNamespace = null, string? className = null)
        {
            _diagnostics = diagnostics ?? new DiagnosticsReporter();
            _output.Clear();
            _indentLevel = 0;
            _includes.Clear();
            _variables.Clear();
            _labelCounter = 0;
            _labelStack.Clear();

            _diagnostics.ReportInfo("Starting MicroASM code generation");

            // Generate header comment
            _output.AppendLine("; MicroASM code generated from μHigh");
            _output.AppendLine("; Generated by μHigh Compiler");
            _output.AppendLine();

            // Process imports and includes
            ProcessImports(program);

            // Generate includes
            foreach (var include in _includes.OrderBy(i => i))
            {
                _output.AppendLine($"#include {include}");
            }
            if (_includes.Any()) _output.AppendLine();

            // Generate state variables
            GenerateStateVariables(program);

            // Generate static data
            GenerateStaticData(program);

            // Generate functions
            GenerateFunctions(program);

            // Generate main entry point if needed
            GenerateMainEntry(program);

            _diagnostics.ReportInfo($"MicroASM code generation completed. Generated {_output.ToString().Split('\n').Length} lines");
            return _output.ToString();
        }

        public string GenerateCombined(List<Program> programs, DiagnosticsReporter? diagnostics = null, string? rootNamespace = null, string? className = null)
        {
            _diagnostics = diagnostics ?? new DiagnosticsReporter();
            _output.Clear();
            _indentLevel = 0;
            _includes.Clear();
            _variables.Clear();

            _diagnostics.ReportInfo("Starting combined MicroASM code generation");

            // Process all imports
            foreach (var program in programs)
            {
                ProcessImports(program);
            }

            // Generate combined header
            _output.AppendLine("; Combined MicroASM code generated from μHigh");
            _output.AppendLine();

            // Generate includes
            foreach (var include in _includes.OrderBy(i => i))
            {
                _output.AppendLine($"#include {include}");
            }
            if (_includes.Any()) _output.AppendLine();

            // Process all programs
            foreach (var program in programs)
            {
                GenerateStateVariables(program);
                GenerateStaticData(program);
                GenerateFunctions(program);
            }

            // Generate main from the first program that has one
            var mainProgram = programs.FirstOrDefault(p => 
                p.Statements.OfType<FunctionDeclaration>().Any(f => f.Name == "main"));
            if (mainProgram != null)
            {
                GenerateMainEntry(mainProgram);
            }

            return _output.ToString();
        }

        public string GenerateWithoutUsings(Program program, DiagnosticsReporter? diagnostics = null, string? rootNamespace = null, string? className = null)
        {
            // MicroASM doesn't have "using" statements like C#, so generate normally
            return Generate(program, diagnostics, rootNamespace, className);
        }

        public HashSet<string> GetCollectedUsings()
        {
            return new HashSet<string>(_includes);
        }

        private void ProcessImports(Program program)
        {
            foreach (var stmt in program.Statements.OfType<ImportStatement>())
            {
                if (stmt.AssemblyName.EndsWith(".masm"))
                {
                    _includes.Add($"\"{stmt.AssemblyName}\"");
                }
                else
                {
                    // Map common imports to MicroASM equivalents
                    var masmInclude = stmt.ClassName switch
                    {
                        "System" => "<stdio.io>",
                        "System.IO" => "<stdio.io>",
                        "System.Math" => "<math.masm>",
                        _ => $"<{stmt.ClassName.ToLower()}.masm>"
                    };
                    _includes.Add(masmInclude);
                }
            }
        }

        private void GenerateStateVariables(Program program)
        {
            var variables = CollectVariables(program.Statements);

            if (variables.Any())
            {
                _output.AppendLine("; State variables");
                foreach (var (name, type, initialValue) in variables)
                {
                    var masmType = ConvertTypeToMasm(type);
                    // Always use STATE for variable declaration
                    if (initialValue != null)
                    {
                        _output.AppendLine($"STATE {name} {masmType} {initialValue}");
                    }
                    else
                    {
                        _output.AppendLine($"STATE {name} {masmType}");
                    }
                    _variables[name] = masmType;
                }
                _output.AppendLine();
            }
        }

        private List<(string name, string type, string? initialValue)> CollectVariables(List<Statement> statements)
        {
            var variables = new List<(string, string, string?)>();

            foreach (var stmt in statements)
            {
                switch (stmt)
                {
                    case VariableDeclaration varDecl:
                        var initialValue = varDecl.Initializer != null ? GenerateExpressionValue(varDecl.Initializer) : null;
                        variables.Add((varDecl.Name, varDecl.Type ?? "int", initialValue));
                        break;
                    case FieldDeclaration fieldDecl:
                        var fieldInitValue = fieldDecl.Initializer != null ? GenerateExpressionValue(fieldDecl.Initializer) : null;
                        variables.Add((fieldDecl.Name, fieldDecl.Type ?? "int", fieldInitValue));
                        break;
                    case ClassDeclaration classDecl:
                        variables.AddRange(CollectVariables(classDecl.Members));
                        break;
                    case NamespaceDeclaration nsDecl:
                        variables.AddRange(CollectVariables(nsDecl.Members));
                        break;
                }
            }

            return variables;
        }

        private string ConvertTypeToMasm(string type)
        {
            return type switch
            {
                "byte" or "sbyte" => "<BYTE>",
                "short" or "ushort" => "<WORD>",
                "int" or "uint" => "<DWORD>",
                "long" or "ulong" => "<QWORD>",
                "float" => "<FLOAT>",
                "double" => "<DOUBLE>",
                "string" => "<PTR>",
                "bool" => "<BYTE>",
                _ => "<QWORD>" // Default to QWORD for unknown types
            };
        }

        private void GenerateStaticData(Program program)
        {
            // Generate string literals and other static data
            var stringLiterals = new List<(string label, string value)>();
            CollectStringLiterals(program.Statements, stringLiterals);

            if (stringLiterals.Any())
            {
                _output.AppendLine("; Static data");
                foreach (var (label, value) in stringLiterals)
                {
                    _output.AppendLine($"{label}: DB \"{EscapeString(value)}\", 0");
                }
                _output.AppendLine();
            }
        }

        private void CollectStringLiterals(List<Statement> statements, List<(string, string)> literals)
        {
            foreach (var stmt in statements)
            {
                CollectStringLiteralsFromNode(stmt, literals);
            }
        }

        private void CollectStringLiteralsFromNode(ASTNode node, List<(string, string)> literals)
        {
            switch (node)
            {
                case LiteralExpression lit when lit.Value is string str:
                    var label = $"str_{literals.Count + 1}";
                    literals.Add((label, str));
                    break;
                case FunctionDeclaration func:
                    foreach (var stmt in func.Body)
                        CollectStringLiteralsFromNode(stmt, literals);
                    break;
                case IfStatement ifStmt:
                    CollectStringLiteralsFromNode(ifStmt.Condition, literals);
                    foreach (var stmt in ifStmt.ThenBranch)
                        CollectStringLiteralsFromNode(stmt, literals);
                    if (ifStmt.ElseBranch != null)
                        foreach (var stmt in ifStmt.ElseBranch)
                            CollectStringLiteralsFromNode(stmt, literals);
                    break;
                // Add more cases as needed for other statement types
            }
        }

        private string EscapeString(string str)
        {
            return str.Replace("\\", "\\\\")
                     .Replace("\"", "\\\"")
                     .Replace("\n", "\\n")
                     .Replace("\r", "\\r")
                     .Replace("\t", "\\t");
        }

        private void GenerateFunctions(Program program)
        {
            var functions = CollectFunctions(program.Statements);
            
            foreach (var func in functions)
            {
                if (func.Name == "main") continue; // Handle main separately
                
                GenerateFunction(func);
            }
        }

        private List<FunctionDeclaration> CollectFunctions(List<Statement> statements)
        {
            var functions = new List<FunctionDeclaration>();

            foreach (var stmt in statements)
            {
                switch (stmt)
                {
                    case FunctionDeclaration func:
                        functions.Add(func);
                        break;
                    case ClassDeclaration classDecl:
                        foreach (var member in classDecl.Members.OfType<MethodDeclaration>())
                        {
                            // Convert method to function
                            var funcDecl = new FunctionDeclaration
                            {
                                Name = $"{classDecl.Name}_{member.Name}",
                                Parameters = member.Parameters,
                                Body = member.Body,
                                ReturnType = member.ReturnType
                            };
                            functions.Add(funcDecl);
                        }
                        break;
                    case NamespaceDeclaration nsDecl:
                        functions.AddRange(CollectFunctions(nsDecl.Members));
                        break;
                }
            }

            return functions;
        }

        private void GenerateFunction(FunctionDeclaration func)
        {
            _output.AppendLine($"; Function: {func.Name}");
            _output.AppendLine($"LBL {func.Name}");

            // Declare local variables using STATE if supported
            foreach (var stmt in func.Body)
            {
                if (stmt is VariableDeclaration varDecl)
                {
                    var masmType = ConvertTypeToMasm(varDecl.Type ?? "int");
                    var initialValue = varDecl.Initializer != null ? GenerateExpressionValue(varDecl.Initializer) : null;
                    if (initialValue != null)
                        _output.AppendLine($"    STATE {varDecl.Name} {masmType} {initialValue}");
                    else
                        _output.AppendLine($"    STATE {varDecl.Name} {masmType}");
                }
            }

            // Function prologue
            if (func.Parameters.Any() || HasLocalVariables(func.Body))
            {
                _output.AppendLine("    PUSH RBP");
                _output.AppendLine("    MOV RBP RSP");
                
                // Allocate space for locals if needed
                var localSize = CalculateLocalSize(func.Body);
                if (localSize > 0)
                {
                    _output.AppendLine($"    SUB RSP {localSize}");
                }
            }

            // Generate function body
            foreach (var stmt in func.Body)
            {
                // Skip variable declarations (already handled above)
                if (stmt is VariableDeclaration) continue;
                GenerateStatement(stmt);
            }

            // Function epilogue
            if (func.Parameters.Any() || HasLocalVariables(func.Body))
            {
                _output.AppendLine("    MOV RSP RBP");
                _output.AppendLine("    POP RBP");
            }
            
            _output.AppendLine("    RET");
            _output.AppendLine();
        }

        private bool HasLocalVariables(List<Statement> statements)
        {
            return statements.Any(s => s is VariableDeclaration);
        }

        private int CalculateLocalSize(List<Statement> statements)
        {
            int size = 0;
            foreach (var stmt in statements)
            {
                if (stmt is VariableDeclaration varDecl)
                {
                    size += GetTypeSize(varDecl.Type ?? "int");
                }
            }
            return (size + 7) & ~7; // Align to 8 bytes
        }

        private int GetTypeSize(string type)
        {
            return type switch
            {
                "byte" or "sbyte" or "bool" => 1,
                "short" or "ushort" => 2,
                "int" or "uint" or "float" => 4,
                "long" or "ulong" or "double" or "string" => 8,
                _ => 8 // Default to 8 bytes
            };
        }

        private void GenerateMainEntry(Program program)
        {
            var mainFunc = program.Statements.OfType<FunctionDeclaration>()
                .FirstOrDefault(f => f.Name == "main");

            if (mainFunc != null)
            {
                _output.AppendLine("; Main entry point");
                GenerateFunction(mainFunc);
            }
            else
            {
                // Generate default main from top-level statements
                var topLevelStatements = program.Statements.Where(s => 
                    !(s is FunctionDeclaration) && 
                    !(s is ClassDeclaration) && 
                    !(s is NamespaceDeclaration) &&
                    !(s is ImportStatement) &&
                    !(s is VariableDeclaration)).ToList();

                if (topLevelStatements.Any())
                {
                    _output.AppendLine("; Generated main from top-level statements");
                    _output.AppendLine("LBL main");
                    foreach (var stmt in topLevelStatements)
                    {
                        GenerateStatement(stmt);
                    }
                    _output.AppendLine("    HLT");
                    _output.AppendLine();
                }
            }
        }

        private void GenerateStatement(Statement stmt)
        {
            switch (stmt)
            {
                case ExpressionStatement exprStmt:
                    GenerateExpressionStatement(exprStmt);
                    break;
                case IfStatement ifStmt:
                    GenerateIfStatement(ifStmt);
                    break;
                case WhileStatement whileStmt:
                    GenerateWhileStatement(whileStmt);
                    break;
                case ForStatement forStmt:
                    GenerateForStatement(forStmt);
                    break;
                case ReturnStatement retStmt:
                    GenerateReturnStatement(retStmt);
                    break;
                case VariableDeclaration varDecl:
                    GenerateVariableDeclaration(varDecl);
                    break;
                case FunctionDeclaration funcDecl:
                    GenerateFunction(funcDecl);
                    break;
                default:
                    _output.AppendLine($"    ; Unsupported statement: {stmt.GetType().Name}");
                    break;
            }
        }

        private void GenerateExpressionStatement(ExpressionStatement exprStmt)
        {
            GenerateExpression(exprStmt.Expression);
        }

        private void GenerateExpression(Expression expr)
        {
            switch (expr)
            {
                case CallExpression callExpr:
                    GenerateCallExpression(callExpr);
                    break;
                case AssignmentExpression assignExpr:
                    GenerateAssignmentExpression(assignExpr);
                    break;
                case BinaryExpression binExpr:
                    GenerateBinaryExpression(binExpr);
                    break;
                case LiteralExpression litExpr:
                    GenerateLiteralExpression(litExpr);
                    break;
                case IdentifierExpression idExpr:
                    GenerateIdentifierExpression(idExpr);
                    break;
            
                
                default:
                    _output.AppendLine($"    ; Unsupported expression: {expr.GetType().Name}");
                    break;
            }
        }

        private void GenerateCallExpression(CallExpression callExpr)
        {
            if (callExpr.Function is IdentifierExpression funcId)
            {
                var functionName = funcId.Name;

                // Use MNI for known native calls
                if (functionName.StartsWith("Memory.") ||
                    functionName.StartsWith("StringOperations.") ||
                    functionName.StartsWith("Math.") ||
                    functionName.StartsWith("IO.") ||
                    functionName.StartsWith("DataStructures.") ||
                    functionName.StartsWith("Network.") ||
                    functionName.StartsWith("Debug.") ||
                    functionName.StartsWith("FileSystem.") ||
                    functionName.StartsWith("System."))
                {
                    _output.Append("    MNI ");
                    _output.Append(functionName);
                    foreach (var arg in callExpr.Arguments)
                    {
                        _output.Append(" ");
                        // If argument is an identifier, use its name
                        if (arg is IdentifierExpression idArg)
                            _output.Append(idArg.Name);
                        // If argument is a literal, use its value
                        else if (arg is LiteralExpression litArg)
                            _output.Append(litArg.Value?.ToString() ?? "0");
                        else
                        {
                            // For other expressions, try to evaluate to a value
                            _output.Append(GenerateExpressionValue(arg));
                        }
                    }
                    _output.AppendLine();
                    return;
                }

                // Handle built-in functions
                switch (functionName)
                {
                    case "print" or "println":
                        if (callExpr.Arguments.Count > 0)
                        {
                            GenerateExpression(callExpr.Arguments[0]);
                            _output.AppendLine("    OUT 1 RAX");
                        }
                        break;
                    default:
                        // Generate arguments (simplified - just first arg in RAX)
                        if (callExpr.Arguments.Count > 0)
                        {
                            GenerateExpression(callExpr.Arguments[0]);
                        }
                        _output.AppendLine($"    CALL #{functionName}");
                        break;
                }
            }
        }

        private void GenerateAssignmentExpression(AssignmentExpression assignExpr)
        {
            // Generate right side first
            GenerateExpression(assignExpr.Value);
            
            // Store to left side
            if (assignExpr.Target is IdentifierExpression idExpr)
            {
                _output.AppendLine($"    MOV {idExpr.Name} RAX");
            }
        }

        private void GenerateBinaryExpression(BinaryExpression binExpr)
        {
            // Simplified: load left into RAX, right into RBX, operate
            GenerateExpression(binExpr.Left);
            _output.AppendLine("    PUSH RAX");
            GenerateExpression(binExpr.Right);
            _output.AppendLine("    MOV RBX RAX");
            _output.AppendLine("    POP RAX");

            switch (binExpr.Operator)
            {
                case TokenType.Plus:
                    _output.AppendLine("    ADD RAX RBX");
                    break;
                case TokenType.Minus:
                    _output.AppendLine("    SUB RAX RBX");
                    break;
                case TokenType.Multiply:
                    _output.AppendLine("    MUL RAX RBX");
                    break;
                case TokenType.Divide:
                    _output.AppendLine("    DIV RAX RBX");
                    break;
                case TokenType.Equal:
                    _output.AppendLine("    CMP RAX RBX");
                    break;
                default:
                    _output.AppendLine($"    ; Unsupported operator: {binExpr.Operator}");
                    break;
            }
        }

        private void GenerateLiteralExpression(LiteralExpression litExpr)
        {
            switch (litExpr.Value)
            {
                case int i:
                    _output.AppendLine($"    MOV RAX {i}");
                    break;
                case string s:
                    // Find the string label
                    var stringLiterals = new List<(string, string)>();
                    CollectStringLiterals(new List<Statement>(), stringLiterals);
                    var label = $"str_{stringLiterals.Count + 1}";
                    _output.AppendLine($"    MOV RAX #{label}");
                    break;
                case bool b:
                    _output.AppendLine($"    MOV RAX {(b ? 1 : 0)}");
                    break;
                default:
                    _output.AppendLine($"    MOV RAX {litExpr.Value}");
                    break;
            }
        }

        private void GenerateIdentifierExpression(IdentifierExpression idExpr)
        {
            _output.AppendLine($"    MOV RAX {idExpr.Name}");
        }

        private void GenerateIfStatement(IfStatement ifStmt)
        {
            var elseLabel = GenerateLabel("else");
            var endLabel = GenerateLabel("endif");

            GenerateExpression(ifStmt.Condition);
            _output.AppendLine("    CMP RAX 0");
            _output.AppendLine($"    JZ #{elseLabel}");

            foreach (var stmt in ifStmt.ThenBranch)
            {
                GenerateStatement(stmt);
            }

            if (ifStmt.ElseBranch != null && ifStmt.ElseBranch.Any())
            {
                _output.AppendLine($"    JMP #{endLabel}");
                _output.AppendLine($"LBL {elseLabel}");
                foreach (var stmt in ifStmt.ElseBranch)
                {
                    GenerateStatement(stmt);
                }
                _output.AppendLine($"LBL {endLabel}");
            }
            else
            {
                _output.AppendLine($"LBL {elseLabel}");
            }
        }

        private void GenerateWhileStatement(WhileStatement whileStmt)
        {
            var loopLabel = GenerateLabel("loop");
            var endLabel = GenerateLabel("endloop");

            _output.AppendLine($"LBL {loopLabel}");
            GenerateExpression(whileStmt.Condition);
            _output.AppendLine("    CMP RAX 0");
            _output.AppendLine($"    JZ #{endLabel}");

            foreach (var stmt in whileStmt.Body)
            {
                GenerateStatement(stmt);
            }

            _output.AppendLine($"    JMP #{loopLabel}");
            _output.AppendLine($"LBL {endLabel}");
        }

        private void GenerateForStatement(ForStatement forStmt)
        {
            if (forStmt.IsForInLoop)
            {
                // Handle for-in loops (simplified)
                _output.AppendLine("    ; For-in loop not fully implemented");
            }
            else
            {
                // Traditional for loop
                if (forStmt.Initializer != null)
                {
                    GenerateStatement(forStmt.Initializer);
                }

                var loopLabel = GenerateLabel("forloop");
                var endLabel = GenerateLabel("endfor");

                _output.AppendLine($"LBL {loopLabel}");
                
                if (forStmt.Condition != null)
                {
                    GenerateExpression(forStmt.Condition);
                    _output.AppendLine("    CMP RAX 0");
                    _output.AppendLine($"    JZ #{endLabel}");
                }

                foreach (var stmt in forStmt.Body)
                {
                    GenerateStatement(stmt);
                }

                if (forStmt.Increment != null)
                {
                    GenerateStatement(forStmt.Increment);
                }

                _output.AppendLine($"    JMP #{loopLabel}");
                _output.AppendLine($"LBL {endLabel}");
            }
        }

        private void GenerateReturnStatement(ReturnStatement retStmt)
        {
            if (retStmt.Value != null)
            {
                GenerateExpression(retStmt.Value);
            }
            _output.AppendLine("    RET");
        }

        private void GenerateVariableDeclaration(VariableDeclaration varDecl)
        {
            // Already handled by STATE in function prologue or global scope
            // Only emit assignment if initializer exists
            if (varDecl.Initializer != null)
            {
                GenerateExpression(varDecl.Initializer);
                _output.AppendLine($"    MOV {varDecl.Name} RAX");
            }
        }

        private string GenerateLabel(string prefix)
        {
            return $"{prefix}_{++_labelCounter}";
        }

        private string GenerateExpressionValue(Expression expr)
        {
            return expr switch
            {
                LiteralExpression lit => lit.Value?.ToString() ?? "0",
                IdentifierExpression id => id.Name,
                _ => "0"
            };
        }
    }
}
