//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uhigh.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uhigh.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH001 means that the compiler ran into a unexpected token while reading the source file/files. check the contents of your program with the error that was provided for more information..
        /// </summary>
        public static string UH001 {
            get {
                return ResourceManager.GetString("UH001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH002 means that the compiler tried to parse a string but didn&apos;t find a closing quote on the same line. check the error that was provided for the source file or line that the error came from..
        /// </summary>
        public static string UH002 {
            get {
                return ResourceManager.GetString("UH002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH003 means that the compiler tried to and failed to parse a number that ether was used in a variable assignment, if expression/equality operator or as a float value. check the error that was provided for more information..
        /// </summary>
        public static string UH003 {
            get {
                return ResourceManager.GetString("UH003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH004 means that the compiler somehow managed to find a unexpected character that was not allowed in the expression that was checked. read the error that was provided for more information..
        /// </summary>
        public static string UH004 {
            get {
                return ResourceManager.GetString("UH004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH005 means that something internal with the token handling inside the compiler broke, please check the error for more infomation..
        /// </summary>
        public static string UH005 {
            get {
                return ResourceManager.GetString("UH005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH006 means that the parser expected an expression but did not find one. Check for missing or misplaced tokens in your code..
        /// </summary>
        public static string UH006 {
            get {
                return ResourceManager.GetString("UH006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH007 means that the parser expected a closing parenthesis, bracket, or brace but did not find one. Check for unbalanced or missing delimiters..
        /// </summary>
        public static string UH007 {
            get {
                return ResourceManager.GetString("UH007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH008 means that the parser encountered an unexpected end of file. This usually means you have an incomplete statement or block..
        /// </summary>
        public static string UH008 {
            get {
                return ResourceManager.GetString("UH008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH009 means that the parser found a duplicate declaration of a variable, function, or class in the same scope..
        /// </summary>
        public static string UH009 {
            get {
                return ResourceManager.GetString("UH009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH010 means that the parser encountered an invalid or unsupported syntax construct. Check the documentation for supported language features..
        /// </summary>
        public static string UH010 {
            get {
                return ResourceManager.GetString("UH010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH011 means that the code generator could not resolve a type or symbol. This may be due to a missing declaration or an unsupported type..
        /// </summary>
        public static string UH011 {
            get {
                return ResourceManager.GetString("UH011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH012 means that the code generator encountered an unsupported operation or expression. This may be a bug or a feature not yet implemented..
        /// </summary>
        public static string UH012 {
            get {
                return ResourceManager.GetString("UH012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH013 means that the code generator failed to emit code for a statement or expression. Check for invalid or incomplete constructs..
        /// </summary>
        public static string UH013 {
            get {
                return ResourceManager.GetString("UH013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH014 means that the code generator detected a circular dependency or infinite recursion in your code..
        /// </summary>
        public static string UH014 {
            get {
                return ResourceManager.GetString("UH014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH015 is a warning that a variable is declared but never used. Consider removing unused variables to clean up your code..
        /// </summary>
        public static string UH015 {
            get {
                return ResourceManager.GetString("UH015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH016 is a warning that a function is declared but never called. Unused functions may indicate dead code..
        /// </summary>
        public static string UH016 {
            get {
                return ResourceManager.GetString("UH016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH017 is a warning that a value is assigned but never read. This may indicate a logic error or unnecessary assignment..
        /// </summary>
        public static string UH017 {
            get {
                return ResourceManager.GetString("UH017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH018 is a warning that an implicit type conversion may result in data loss or unexpected behavior..
        /// </summary>
        public static string UH018 {
            get {
                return ResourceManager.GetString("UH018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH019 is a warning that a deprecated feature or syntax is used. Consider updating your code to use recommended alternatives..
        /// </summary>
        public static string UH019 {
            get {
                return ResourceManager.GetString("UH019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH020 means that the compiler detected unreachable code after a return, break, or continue statement..
        /// </summary>
        public static string UH020 {
            get {
                return ResourceManager.GetString("UH020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH021 means that the parser found an invalid identifier name. Identifiers must start with a letter or underscore and contain only letters, digits, or underscores..
        /// </summary>
        public static string UH021 {
            get {
                return ResourceManager.GetString("UH021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH022 means that the code generator encountered an attempt to divide by zero, which is not allowed..
        /// </summary>
        public static string UH022 {
            get {
                return ResourceManager.GetString("UH022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH023 means that the compiler detected a possible null reference usage. Ensure the variable is initialized before use..
        /// </summary>
        public static string UH023 {
            get {
                return ResourceManager.GetString("UH023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH024 means that the parser found a function or method call with the wrong number of arguments..
        /// </summary>
        public static string UH024 {
            get {
                return ResourceManager.GetString("UH024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH025 means that the compiler encountered an unsupported escape sequence in a string literal..
        /// </summary>
        public static string UH025 {
            get {
                return ResourceManager.GetString("UH025", resourceCulture);
            }
        }
    }
}
